### ISSUE TITLE
Cloned Repo and I get Error: Failed to acquire configuration: Keycloak is misconfigured

### ISSUE THREAD

**Issue by CodeNameNinja** [bcgov/vue-scaffold#14]
I cloned the repo and followed the installtion steps closely and I keep getting

Error: Failed to acquire configuration: Keycloak is misconfigured

I know my keycloak api requests are working and all the urls in the config are fine, not sure why this is happening.

this seems to be an issue in main.js getting the config correctly

**Comment by jujaga** [comment]
Hi @CodeNameNinja,

The Keycloak is misconfigured error likely means that you haven't supplied all the custom environment variables necessary for the application to run. The `custom-environment-variables.json` file provides a complete mapping of ENV variables to the config that the node application will see, and the `default.json` provides generic defaults for all non-sensitive config values. If you are running this on a local machine, you'll need to create a `local.json` file the values you want set in the same directory as `custom-environment-variables.json`. For more information on how the config library loads and searches for environment variables, take a look at this article: <https://github.com/lorenwest/node-config/wiki/Configuration-Files>.

At an absolute bare minimum, you will want your `local.json` to at least have the following values defined:

```json
{
  "frontend": {
    "keycloak": {
      "clientId": "REDACTED",
      "realm": "REDACTED"
    }
  },
  "server": {
    "keycloak": {
      "clientId": "REDACTED",
      "publicKey": "REDACTED",
      "realm": "REDACTED",
      "clientSecret": "REDACTED"
    },
    "logLevel": "debug",
    "morganFormat": "dev"
  }
}

```

You may need more configured depending on your own personal environments. Hope that helps.

**Comment by CodeNameNinja** [comment]
No this did not work
its still complaining that keycloak is misconfigured


{
  "frontend": {
    "keycloak": {
      "clientId": "REDACTED",
      "realm": "REDACTED",
      "serverUrl": "REDACTED"
    }
  },
  "server": {
    "apiPath": "/api/v1",
    "baseUrl": "http://localhost:8080",
    "basePath" : "/",
    "bodyLimit": "30mb",
    "keycloak": {
      "clientId": "REDACTEDt",
      "clientSecret": "REDACTED",
      "serverUrl": "REDACTED",
      "realm": "REDACTED"
    },
    "logLevel": "debug",
    "morganFormat": "combined",
    "port": "8080"
  }
}


this is essentially what I have in my default.json and custom-environment-variables.json

**Comment by CodeNameNinja** [comment]
Make NODE_ENV production seemed to resolve my issue
