### ISSUE TITLE
Configuration guide needed

### ISSUE THREAD

**Issue by MGCataldo** [bcgov/vue-scaffold#17]
Hello contributors,

I'm really interested in testing this vue-scaffold, I'm having some problems in understanding well the "custom-environment-variables.json" because I cannot find all the places where the variables in the files are used.
Just for example  I cannot find where "the frontend is mounted on the /app path".
Is there any example to help me?
thanks

**Comment by jujaga** [comment]
The `custom-environment-variables.json` file provides a complete mapping of ENV variables to the config that the node application will see, and the `default.json` provides generic defaults for all non-sensitive config values. If you do a search for `config.get(...)` on the repository, you'll get a sense of how the configuration variables are utilized.

If you are running this on a local machine, you'll need to create a `local.json` file the values you want set in the same directory as `custom-environment-variables.json`. For more information on how the config library loads and searches for environment variables, take a look at this article: <https://github.com/lorenwest/node-config/wiki/Configuration-Files>. 

At an absolute bare minimum, you will want your `local.json` to at least have the following values defined:

```json
{
  "frontend": {
    "keycloak": {
      "clientId": "REDACTED",
      "realm": "REDACTED"
    }
  },
  "server": {
    "keycloak": {
      "clientId": "REDACTED",
      "publicKey": "REDACTED",
      "realm": "REDACTED",
      "clientSecret": "REDACTED"
    },
    "logLevel": "debug",
    "morganFormat": "dev"
  }
}

```

You may need more configured depending on your own personal environments. Hope that helps.

**Comment by MGCataldo** [comment]
Thanks Jeremy.

Don't you think that the additional variables below are also necessary at a bare minimum?

- keycloak.serverUrl
- server.port
- server.keycloak.serverUrl

Best Regards

**Comment by jujaga** [comment]
> 
> 
> Thanks Jeremy.
> 
> Don't you think that the additional variables below are also necessary at a bare minimum?
> 
>     * keycloak.serverUrl
> 
>     * server.port
> 
>     * server.keycloak.serverUrl
> 
> 
> Best Regards

Assuming you are using your own Keycloak provider, you will want to define your own `keycloak.serverUrl` and `server.keycloak.serverUrl` values instead of using one pre-defined for BCGov. The value `server.port` does not exist as that would be embedded as part of the serverUrls directly if necessary.

**Comment by MGCataldo** [comment]
Thank you Jeremy for your valuable support! 

I'm using node since an year and this is my first time with "full-stack application which self-hosts the Vue frontend and consumes its API endpoint". I got really excited when I found this repository because it was exactly what I guess covers my needs for BioIngeenering laboratory I work .

I'm a bit confused with some of the configuration keys, I don't know exactly what to supply to the application. 
I think that a description for them would help me and others to better  understand and adopt the repository as valuable template
We use our instance of keycloack. 

{
  "frontend": {
    "apiPath": "FRONTEND_APIPATH",   
    "basePath": "FRONTEND_BASEPATH",
    "keycloak": {
      "clientId": "FRONTEND_KC_CLIENTID",
      "realm": "FRONTEND_KC_REALM",
      "serverUrl": "FRONTEND_KC_SERVERURL"
    }
  },
  "server": {
    "apiPath": "SERVER_APIPATH",
    "basePath" : "SERVER_BASEPATH",
    "bodyLimit": "SERVER_BODYLIMIT",
    "keycloak": {
      "clientId": "SERVER_KC_CLIENTID",
      "clientSecret": "SERVER_KC_CLIENTSECRET",
      "publicKey": "SERVER_KC_PUBLICKEY",
      "realm": "SERVER_KC_REALM",
      "serverUrl": "SERVER_KC_SERVERURL"
    },
    "logFile": "SERVER_LOGFILE",
    "logLevel": "SERVER_LOGLEVEL",
    "morganFormat": "SERVER_MORGANFORMAT",
    "port": "SERVER_PORT"
  },
  "serviceClient": {
    "commonServices": {
      "ches": {
        "endpoint": "SC_CS_CHES_ENDPOINT"
      },
      "cdogs": {
        "endpoint": "SC_CS_CDOGS_ENDPOINT"
      },
      "tokenEndpoint": "SC_CS_TOKEN_ENDPOINT",
      "username": "SC_CS_USERNAME",
      "password": "SC_CS_PASSWORD"
    }
  }
}

Thank you a lot
Best Regards
Maurizio

**Comment by MGCataldo** [comment]
Hi Jeremy,

I've written in the issue page of the repository the request for
explanation you can find below, I've put the request there because I think
the answer would be interesting also for others that like me are likely to
implement it.
I'm writing to you now because I want to be sure to behave correctly, not
to bother you or ask for support that you can't offer. In the latter case I
apologize, just let me know and, if you can, just suggest how to better
understand the project structure.
The vue-scaffold is really interesting, my congratulation, I just miss some
project description/guide to go faster in implementing it.


FRONTEND_APIPATH= // ...?? need example

FRONTEND_BASEPATH= // OK the URL vue application path, ie: "/demo" results
> in: http://localhost:8080:/demo
> <http://localhost:8080/demo>

FRONTEND_KC_CLIENTID= // OK my keycloack clientID

FRONTEND_KC_REALM= // OK my keycloack Realm

FRONTEND_KC_SERVERURL= // OK my keycloack SERVER URL

SERVER_APIPATH= // ...?? don't understand what's for

SERVER_BASEPATH= // ...?? need example

SERVER_BODYLIMIT= // ...?? need example

SERVER_KC_CLIENTID= // ...?? need example

SERVER_KC_CLIENTSECRET= // ...?? need example

SERVER_KC_PUBLICKEY= // ...?? need example

SERVER_KC_REALM= // ...?? need example

SERVER_KC_SERVERURL= // ...?? need example

SERVER_LOGFILE= // ...?? need example

SERVER_LOGLEVEL= // ...?? need example

SERVER_MORGANFORMAT= // ...?? need example

SERVER_PORT= // ...?? need example

SC_CS_CHES_ENDPOINT= // ...?? need example

SC_CS_CDOGS_ENDPOINT= // ...?? need example

SC_CS_TOKEN_ENDPOINT= // ...?? need example

SC_CS_USERNAME= // ...?? need example

SC_CS_PASSWORD= // ...?? need example



> Hope I'm not asking too much.


Thank very much
Best Regards
Maurizio

------------------------------

Gennaro Maurizio Cataldo

Laboratorio di Bioingegneria
Dipartimento di Biotecnologie Mediche - Settore Ricerca

Università di Siena
tel. +39-0577-585736 - email: ***@***.***

------------------------------



Il giorno mar 4 mag 2021 alle ore 18:49 Jeremy Ho ***@***.***>
ha scritto:
