### ISSUE TITLE
crbug/1173575, non-JS module files deprecated.

### ISSUE THREAD

**Issue by MGCataldo** [bcgov/vue-scaffold#20]
Hi,
Since a couple of weeks I've seen the error "crbug/1173575, non-JS module files deprecated." for some browser instances.
It happens in different browsers, tested chrome, edge, firefox and also for the same browser: in chrome I've two different instance of the chrome desktop app, one connected to a given Google Account and another connected to a different google account, The app works well enough with the first chrome instance and return the error for the second.
The app does show the issue with firefox, edge and of course also chrome (for the second instance...)

I'm running VSCode on: 
Windows 10,
node 14.17.0,
vue/cli 4.5.13,
vue 2.6.14

any idea?

**Comment by MGCataldo** [comment]
Close

**Comment by ibra0301** [comment]
I have the same problem ,did you find a solution.
