### ISSUE TITLE
Keycloak setup

### ISSUE THREAD

**Issue by thecch** [bcgov/vue-scaffold#7]
Any chance you have documentation on keycloak config? Or the config file to import into keycloak directly

**Comment by jujaga** [comment]
Hi @burn874 . I don't think we have any explicit documentation in regards on how to set up Keycloak. However, provided that you are an administrator of at least one Keycloak realm, the vue-scaffold application will only require 2 clients (3 if you want to handle local development). The first client would service the backend, the second client would be for the frontend, and the 3rd development one would be the same as the second client, but allow a localhost redirect instead.

As far as configuring this scaffold application, as long as all the environment variables are specified as defined `custom-environment-variables.json`, the application will be able to run. You can alternatively specify and populate a `local.json` file in the same directory with the appropriate values, and the application will pick up that information on startup. In relation to keycloak, if the values in `frontend.keycloak.*` and `server.keycloak.*` are defined, you should be able to authenticate. This project uses the [npm config](https://www.npmjs.com/package/config) library, so for more details on how to config, look for their documentation there. Hope this helps.
